server:
  port: 2001

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: gle-rabbit
    password: lXcKV_-WN1sA+FwXiOrx

hello:
  world:
    queue: hello.world.queue

publish:
  queue: publish.queue
  queue-2: publish.queue-2
  exchange: publish.exchange